### ISSUE TITLE
String replacement block

### ISSUE THREAD

**Issue by onli** [pipes-digital/pipes#10]
Have a block that allows to replace strings in the input feed (or the input data after #8).

**Comment by onli** [comment]
Now added, https://www.pipes.digital/docs#replace is its documentation.

**Comment by anewuser** [comment]
Leaving out the keyword and replacement fields blank gives gives an "Internal Server Error" when you access the generated feed.

**Comment by onli** [comment]
Thanks. I added a safeguard for that. It will now just ignore the block in that case.
