### ISSUE TITLE
No feedback after a pipe was duplicated on Firefox

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#101]
After duplicating a pipe with Vivaldi, it correctly redirected to the new copy, as expected.

For some reason, this isn't happening on Firefox. It creates the copy, but stays on the original page with no "success" message. I could reproduce this with a clean Firefox profile.

**Comment by anewuser** [comment]
Hello. Sorry for being missing for long. This issue doesn't exist anymore.

**Comment by onli** [comment]
Awesome. And welcome back!
