### ISSUE TITLE
Public Pipes

### ISSUE THREAD

**Issue by onli** [pipes-digital/pipes#12]
This is a long term goal.

So far, Pipes is focussing on creating the actual pipe, the editor and their blocks. But it would also be good to mirror the community features: To have public pipes that can be described, shared, upvoted, commented and, most important, forked. 

This would also help new users, by showing them how Pipes can be used.

**Comment by anewuser** [comment]
Until you implement this, accessing a pipe without being logged in should display the login prompt or redirect the user to a blank pipe instead of keeping the pipe address in the URL bar. For example, if you try to access this anonymously: https://www.pipes.digital/editor/j1O4yeqd

**Comment by onli** [comment]
Good idea. Done.

Be aware that a logged in user can already see the editor content. He can save nothing, but the blocks are not hidden.

**Comment by onli** [comment]
Public pipes now live under https://www.pipes.digital/pipes. On https://www.pipes.digital/mypipes one can share a pipe, set its tags and the description.
