### ISSUE TITLE
401 server error when attempting to view output

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#13]
I get "No result" when trying to work with feeds from Youtube. Example URL: https://www.youtube.com/feeds/videos.xml?channel_id=UCoxg3Kml41wE3IPq-PC-LQw

**Comment by onli** [comment]
Hi, thanks for reporting this bug. I will look into this soon.

**Comment by onli** [comment]
Okay, the feed itself is working for me. I added the exact link you showed into a feed block, then connected that one to a filter block, and the output looks sound to me. Could you please explain a bit more at which point in your pipe it breaks? A screenshot of the pipe could also be useful.

**Comment by onli** [comment]
Oh, I think you run in an UI error. Did you already login, by trying to save the pipe or going to the my pipes page before? View output actually executes the pipe up to this block, and is thus protected by the login. 

If it is that there should be at least a prompt to login when using the viewer.

**Comment by anewuser** [comment]
I logged in now and it worked. I just wanted to test it before entering an email address, but got no prompt to do that, just the error message:

![untitled-1](https://user-images.githubusercontent.com/6733770/28192698-39799508-680e-11e7-9101-427a6744e88a.png)

**Comment by onli** [comment]
The next version will show an error message. I'll close here already for overview.
