### ISSUE TITLE
restriction of users?

### ISSUE THREAD

**Issue by Krotosz6** [pipes-digital/pipes#132]
Is there any way to limit the number of logins or the IP limit from which I can log in?

**Comment by onli** [comment]
Hi @Krotosz6 Do you run pipes-ce yourself and want to limit it, or is it about an account on pipes.digital?

For pipes.digital you would use your email address, for example rely on the account protection of gmail. I'm not sure that an IP limit is possible that way, but 2FA is.

Same thing if you host pipes-ce yourself. But then you could also change the configured portier broker to a self-hosted instance, which you can then protect however you want. To set this custom portier broker url you would edit the server.rb and add `set :browserid_url, "http_path_of_the_broker"` somewhere near the other configuration lines. Not ideal, but should work.

See https://github.com/portier/sinatra-portier for some information on how to configure the portier gem, and https://github.com/portier/portier-broker for the broker itself.

**Comment by Krotosz6** [comment]
> Hi @Krotosz6 Do you run pipes-ce yourself and want to limit it

Exactly. I would like only to trusted users. 

> 
> For pipes.digital you would use your email address, for example rely on the account protection of gmail. I'm not sure that an IP limit is possible that way, but 2FA is.
> 
> Same thing if you host pipes-ce yourself. But then you could also change the configured portier broker to a self-hosted instance, which you can then protect however you want. To set this custom portier broker url you would edit the server.rb and add `set :browserid_url, "http_path_of_the_broker"` somewhere near the other configuration lines. Not ideal, but should work.

thanks. I will try it. :)

> 
> See https://github.com/portier/sinatra-portier for some information on how to configure the portier gem, and https://github.com/portier/portier-broker for the broker itself.

thanks :)

**Comment by onli** [comment]
I assume this is solved and close the issue. Please just re-open if the issue remains.
