### ISSUE TITLE
Custom favicons

### ISSUE THREAD

**Issue by mbologna** [pipes-digital/pipes#133]
My feed reader show the favicon of pipes.digital, is there a way to build a feed and to specify a custom favicon?

**Comment by mbologna** [comment]
I think that the solution would be to manipulate the feed produced by pipes.digital and declare the favicon in the feed like this:

```
<link rel="shortcut icon" href="website_source/favicon.ico" type="image/x-icon" />
```

**Comment by onli** [comment]
Oh, that'd be interesting. Could you point me to a feed that uses this solution?

**Comment by mbologna** [comment]
> Oh, that'd be interesting. Could you point me to a feed that uses this solution?

I don't have an example that I know but I 

> Oh, that'd be interesting. Could you point me to a feed that uses this solution?

I have done [an experiment](https://www.michelebologna.net/tmp/arstechnica_tmp/feed.xml) but it does not work, as the browser will look in `/favicon.ico` nevertheless.

**Comment by onli** [comment]
Ha, good idea to just put up a modified textfile. Sad that it did not work.

Should we close here, and re-open if we stumble over a solution?

**Comment by mbologna** [comment]
I just found out that another application (RSS Filter) manipulates a feed while keeps the original favicon/logo.
Example: if you add https://rssfilter-a7aj2utffa-uc.a.run.app/feed?title_allow=Google&url=https%3A%2F%2Fwww.arstechnica.com%2Ffeed%2F to your feed reader, it shows the original site logo.

I believe that the feed built by pipes.digital is missing the `<image>`:

```
<channel>
        <image>
            <url>
                https://cdn.arstechnica.net/wp-content/uploads/2016/10/cropped-ars-logo-512_480-32x32.png</url>
            <title>Ars Technica</title>
            <link>https://arstechnica.com</link>
            <width>32</width>
            <height>32</height>
        </image>
```

(in case of combined feed, just replicate the first feed's `<image>`. What do you think?

**Comment by mbologna** [comment]
> As a last step of your pipe, take the original feed and extract the image element (path: `/rss/channel/image`, attribute: `OuterXml`) and insert this into your feed with the insert block (at `/rss/channel`).

I added the workaround for the `<image>` tag:
![image](https://github.com/pipes-digital/pipes/assets/530992/9b4b011d-1658-4860-8bb9-514e281d97d7)
but it returns a HTTP 500: https://www.pipes.digital/feedpreview/pqwY2wNB
 
> Because on a first look, it seems like the feed parser library Pipes use drops the image element completely, so this would be linked to the bigger question of how to not parse the data like this when going from block to block, or at least would need a parser extension.

What parser library is Pipes using?

**Comment by onli** [comment]
Hm, I went into the logs and don't understand the error. It's the insert block that claims it sees no element?

Try it from here: https://www.pipes.digital/pipe/POdv0L9D. That pipe works for me, it should be possible to extend it feed by feed. Maybe we can pinpoint like this where the error is.

> What parser library is Pipes using?

Pipes is running the feeds through https://github.com/rubycocos/feedparser/tree/master/feedparser for normalization

**Comment by mbologna** [comment]
> Hm, I went into the logs and don't understand the error. It's the insert block that claims it sees no element?

I don't see any error from the UI either.

> Try it from here: [pipes.digital/pipe/POdv0L9D](https://www.pipes.digital/pipe/POdv0L9D). That pipe works for me, it should be possible to extend it feed by feed. Maybe we can pinpoint like this where the error is.

I added the feed in Feedly but the feed icon is not shown. Maybe because the `<image>` tag is towards the end?

**Comment by onli** [comment]
> I added the feed in Feedly but the feed icon is not shown. Maybe because the <image> tag is towards the end?

That shouldn't matter, I would expect the feed reader to parse the whole file and the position doesn't matter in XML. But you are right! It doesn't work also in FreshRSS. Did we miss something else?

**Comment by mbologna** [comment]
Seems like Ars' feed is XML not valid right now.
Can you please retry with something else, like https://openrss.org/www.theverge.com ?

**Comment by onli** [comment]
It's the link element!

The feed has this in it:

```
?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="/www.theverge.com/.xsl"?>
<rss version="2.0">
  <channel>
    ...
    <link><![CDATA[https://arstechnica.com/]]></link>
```
The image element is ignored, but depending on the link element the favicon of the linked site gets selected. At least in FreshRSS. It's a bit hard to test because changing the element in an already subscribed file did not change the favicon for me, but creating a new feed with changed links works as expected. I set in `https://pipes.digital` and it switched.

Can you confirm that?

Changing the link element of the channel should be something we can also do with an insert block :)

**Comment by onli** [comment]
Did you try it directly with that feed, or did you modify the output to change the link element? The needed modification is not done there yet

**Comment by onli** [comment]
It's not quite correct I think, because this will set a second link element. Instead replace the content of the old one:

![Screenshot 2024-01-25 at 14-39-51 Editor Pipes](https://github.com/pipes-digital/pipes/assets/900380/e76e68bc-7ea2-44ea-84d6-d060b57a27bb)

I changed it in https://www.pipes.digital/pipe/POdv0L9D and it worked for me! :)

**Comment by mbologna** [comment]
> I changed it in [pipes.digital/pipe/POdv0L9D](https://www.pipes.digital/pipe/POdv0L9D) and it worked for me! :)

I tried this one in Feedly and I still see pipes.digital's favicon. I guess Feedly uses a different criteria?

**Comment by onli** [comment]
Hm. They might use the `atom10:link` element instead. Or the old icon is cached for that feed. Maybe try it once more in a different pipe?

**Comment by mbologna** [comment]
> ![Screenshot 2024-01-25 at 14-39-51 Editor Pipes](https://private-user-images.githubusercontent.com/900380/299684406-e76e68bc-7ea2-44ea-84d6-d060b57a27bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTU3MDcsIm5iZiI6MTcwNjE5NTQwNywicGF0aCI6Ii85MDAzODAvMjk5Njg0NDA2LWU3NmU2OGJjLTdlYTItNDRlYS04NGQ2LWQwNjBiNTdhMjdiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQxNTEwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzBhOGNkMTgxNWJhMWI2YjI2ZmJmZjdmYjY4YjFkMzI1ZTdiNDAxMzA1ZGY0OWU5MjQzMDUyY2M3ZDQ4YjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bYFkL9KZ36ceeFIwSvvy5r9tk-KCtBsjOyW-susIyHc)

I duplicated the feed above and I can confirm it is working, so likely a caching issue on Feedly. Thanks a lot for the shared debugging and the solution, it was fun!

**Comment by mbologna** [comment]
Yes this is a workaround, at least, until the dependency library can be instructed to fetch the `<link>`.
