### ISSUE TITLE
Unknown wrong feed shown in preview

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#16]
While previewing a feed block with the URL  set to `http://www.radiofreesatan.com/` (for [this pipe](https://www.pipes.digital/feed/REOmjQqL)), I got posts from some unrelated Russian download site  I never used instead. The pipe worked as expected though.

After reloading the preview a couple of times, the correct feed was displayed.

![Screenshot of the problem](https://user-images.githubusercontent.com/6733770/28286111-7cdc1a30-6b0d-11e7-89f3-0ed26552dc9a.png)

<details>
  <summary>Click to see preview code</summary>

    <rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:trackback="http://madskills.com/public/xml/rss/module/trackback/">
    <channel>
    <title>
    Extracted Content
      </title>
    <link>
     
      </link>
    <description>
     
      </description>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    3e72096fcad5367b822003c89ec0a3a9
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Мертвец детектива Мегрэ / Maigret's Dead Man (2016) BDRip [H.264/720p] [MVO]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.352014+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    ff9887707dc1fc446edb5a73c780e582
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Это всего лишь конец света / Juste la fin du monde (It's Only the End of the World) (2016) Blu-ray [H.264/1080p] [Custom]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.352549+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    5d2a14d0525518cfb5791d960970de7b
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Чего хотят женщины / What Women Want (2000) BDRip [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.353055+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    e38c41f9650b41f52336d4619e77ed1d
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Обещание / The Promise (2016) Blu-ray [H.264/1080p] [Custom]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.35361+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    d1f8ceb0ce4d8dbeaebdd60ddf2f30c6
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Преследование / Following (1998) BDRip [H.264/720p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.354155+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    a0a89f1c29bd5c0549f2ca6e53873e89
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Шальная карта / Wild Card (2015) BDRemux [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.354739+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    b4af65cef6b1c78002b73d1928683ddd
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Индиана Джонс и Королевство xрустального черепа / Indiana Jones and the Kingdom of the Crystal Skull (2008) BDRip [H.264/720p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.355288+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    67b63ed8fef8cc4bb2b7a0d5e8603640
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Фото за час / One Hour Photo (2002) BDRemux [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.355841+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    e2fe2f6a2193cb19240d55ea6d524b78
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Обещание / The Promise (2016) BDRip [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.356386+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    11edaaa6d583cea044737760b42d9c24
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Я очень возбужден / Los amantes pasajeros (2013) BDRip [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.356889+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    3c760dcc0251cad9a77208c7d47e9a1c
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Пустоголовые / Airheads (1994) BDRip [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.357406+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    fe8d0cc7711a18a04611e4ac960e3500
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Свадьба лучшего друга / My Best Friend's Wedding (1997) BDRip [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.35793+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    211a04596ff17d3efacc0ba1fcb34f2f
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Молодость по страховке / Wild Oats (2016) BDRip [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.358429+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    fb9267305bbf446647129012585fdabf
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Газонокосильщик / The Lawnmower Man (1992) BDRip [H.264/720p] [Director's Cut]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.359014+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    7a0bf537ac57147ac5f12e2fabfc3960
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Что скрывает ложь / What Lies Beneath (2000) BDRip [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.359548+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    4e1105e7b046eef0bfa18b77945afe4b
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Газонокосильщик / The Lawnmower Man (1992) BDRip [H.264/1080p] [Director's Cut]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.360069+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    fe4f3ecb914cfc4495e951b606859a54
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Мумия / The Mummy (1999, 2001) HDDVDRemux [VC-1/1080p] [Дилогия]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.360637+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    379a4bebd340b51c746156f4780ebd39
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Свет вокруг / И все осветилось / Все озарено / Everything Is Illuminated (2005) WEB-DL [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.361282+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    82d0e601767308fc302c6fd8a7b14b1f
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Их собственная лига / A League of Their Own (1992) Blu-ray [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.361809+00:00
      </dc:date>
    
        
      </item>
    <item>
    <title>
    Extracted Content
      </title>
    <pubDate>
    Mon, 17 Jul 2017 19:14:17 +0000
      </pubDate>
    <guid>
    4a142e8df22f3d79ddb26999deb14d1e
      </guid>
    <content:encoded>
    Зарубежные Фильмы (HD, UHD-LQ) :: Волынь / Wolyn (2016) BDRemux [H.264/1080p]
      </content:encoded>
    <dc:date>
    2017-07-17T19:14:17.36237+00:00
      </dc:date>
    
        
      </item>
    <dc:date>
    2017-07-17T19:14:17.351285+00:00
      </dc:date>
    
      
      </channel>
    
      </rss>
</details>

**Comment by onli** [comment]
This should be fixed now.

What I think happened: Pipes are cached. When using the preview, the system creates a temporary pipes to execute the block and all the blocks before it. That one had no id, and not having an id was not properly detected, thus the system happily cached under the empty id. So when you executed the preview of the block he showed you the cache of one other block, from a different user and pipe.

I'm really not happy that one slipped through. But thanks a lot for reporting this!
