### ISSUE TITLE
Media enclosures not attached to output feed

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#17]
https://www.pipes.digital/feed/REOmjQqL has no media enclosures, despite being formed just by:

Feed block (URL: `http://www.radiofreesatan.com/`) ->  Filter block (String: `/breakfast/i`) -> Out

Both blocks still show the mp3 files in their preview.

**Comment by onli** [comment]
Yes. We normalize the feeds when being given to a block, and this normalization strips the media enclosure. It would be good to keep it in there, at least as silent payload.

**Comment by anewuser** [comment]
I see. This really is needed for podcast feeds, so that we don't have to manually open the original URL to download each new episode.

**Comment by onli** [comment]
Short update: I sent a PR to the normalization gem pipes uses that makes the enclosure accessible. I'll give upstream some time to merge this to avoid having to fork, but one way or another enclosure support will come.

**Comment by onli** [comment]
Media enclosure support is now live, and it works in https://www.pipes.digital/feed/REOmjQqL for me.

I'm sorry that it took so long.

**Comment by anewuser** [comment]
Thank you!
