### ISSUE TITLE
Technical Documentation or paper/journal/scientific publication

### ISSUE THREAD

**Issue by centeio** [pipes-digital/pipes#18]
Hi. I'm doing some preliminary research on visual programming and domain-specific languages. I aim to build a new DSL to connect some components as blocks. I found your amazing work and I would like to know if there's any scientific publication and/or some technical documentation I could read and make a reference in my research.
Best,
Carolina

**Comment by onli** [comment]
Hi Carolina, sorry, there is nothing online. You can deduce a bit from https://www.pipes.digital/docs. Making an academical style article is not a bad idea, but that would be something for the future. If you have specific questions, feel free to send me a mail (info@pipes.digital).

**Comment by anewuser** [comment]
@centeio Este projeto foi inspirado pelo extinto Yahoo Pipes, que foi abordado numa série de artigos acadêmicos úteis para a sua pesquisa: https://scholar.google.com/scholar?q=%22yahoo+pipes%22

**Comment by centeio** [comment]
@onli thank you so much!

**Comment by centeio** [comment]
@anewuser eu sei disso, mas há diferenças e o Pipes sendo mais recente, deve ter uma implementação mais recente também. Obrigada!
