### ISSUE TITLE
Edit public description

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#24]
It seems that currently you can only edit the public description of a feed if you make it private then share it again, right?

I've also edited the title of this pipe to "Dark music on Youtube", but it's not displayed in the feed:

https://www.pipes.digital/editor/DpOrjQOw
https://www.pipes.digital/feed/DpOrjQOw

**Comment by onli** [comment]
> It seems that currently you can only edit the public description of a feed if you make it private then share it again, right?

Right. 

> I've also edited the title of this pipe to "Dark music on Youtube", but it's not displayed in the feed

Ah, I never had the idea to use the pipe title as the title of the feed. So far, pipes uses the title of the original input feed.

**Comment by anewuser** [comment]
The description could come from what we've entered in the public description too. That feed currently has this:

    <description>&amp;</description>

**Comment by onli** [comment]
The description is now editable on the new dedicated page each pipe has. You should have an edit button on https://www.pipes.digital/pipe/DpOrjQOw, right next to it.
