### ISSUE TITLE
Combine block does not append pubDate per item

### ISSUE THREAD

**Issue by GJvM-NL** [pipes-digital/pipes#25]
When combining two or more feeds the resulting feed doesn't show a pubDate per item. 
The sort block strips the date too.
Am I missing something?

**Comment by onli** [comment]
You are not making a mistake, the blocks are simply ignoring the pubDate for now and only setting updated. I will look into adding pubDate to the list.

**Comment by onli** [comment]
The blocks were indeed simply not looking at the pubDate. I added that now, and it seemed to work fine in my tests. I'd be happy if you could confirm that it works for you now :)

**Comment by GJvM-NL** [comment]
It works fine. Thank you very much!

**Comment by onli** [comment]
Thanks for reporting the issue!
