### ISSUE TITLE
New update made a filter stop working

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#27]
Hey. You've recently added a new "search in fields:" option to the filter block, right? It let a lot of posts with "trailer" in the title, for example, to get through my pipe and appear on my RSS reader, even though the keyword "trailer" is listed among my blacklisted terms. 

I've solved this by just opening the pipe and pressing "Save" without changing anything. After reloading the feed, those posts were filtered again. Anyway, I thought that you might like to know about this problem.

![Unfiltered pipe](https://user-images.githubusercontent.com/6733770/29923178-ebfc49b4-8e2e-11e7-89c2-1a30bcdd1309.png)

**Comment by onli** [comment]
Thanks for the report, and sorry about the bug. 

This should be fixed now. Since I guess that will be difficult for you to confirm, I'll just close. the report right now, but ask anyone experiencing the bug to re-open this issue.
