### ISSUE TITLE
"No Result" from "View Output"

### ISSUE THREAD

**Issue by derekvaughan** [pipes-digital/pipes#28]
When I try to "View Output", I only get "No Result".  Here is my feed:
https://www.pipes.digital/editor/ZnqxJ8N8

The feed does give a valid output, so I know it is working.
https://www.pipes.digital/feed/ZnqxJ8N8

The same is true when I try to create a new feed.  I tried in both Firefox and Chrome, and got the same result.

**Comment by onli** [comment]
Thanks for reporting that bug. I just pushed a fix, and would be happy if you could confirm that it works for you.

Background: For the text input blocks that enable dynamic pipes the server has to look at the GET parameters when generating a block. That parameter was not passed when generating the temporary blocks the inspector use, the pipe thus died.

**Comment by derekvaughan** [comment]
Yes, the "View Output" is working correctly again.  Thank you for the quick response!

**Comment by derekvaughan** [comment]
I have added a Replace module to the same pipe and the "View Output" stopped working again.  If I get rid of the Replace module, the "View Output" works again.

PS: I am not sure if my use of the Replace module is correct.  The RSS feeds use the <description> tag.  I was trying to replace all instances with <content:encoded> to ensure the article descriptions were preserved.

**Comment by onli** [comment]
Hi. Just wanted to confirm that I see the issue. I'm not sure yet why this is happening, but it seems to be unrelated to what the replace block actually does.

**Comment by derekvaughan** [comment]
Sorry, I removed the Replace module yesterday.  The View Output then works normally.  As soon as I add a Replace or Filter module, even if I do not hook it up, View Output stops working.  I have added the Replace module back in again and hit save.

**Comment by onli** [comment]
That you removed the block is no problem.

To get the content of the "View Output", the browser is sending a long GET request to the server. Something on the production server (probably nginx) seems to have a size limit for that, which we reach when we add the request block. I was so far unsuccessful in raising the limit and might have to implement a workaround.

**Comment by onli** [comment]
@derekvaughan I psuhed a workaround that fixes this for me. Can you confirm that?

**Comment by derekvaughan** [comment]
Yes, it works on my end as well.  Thank you!
