### ISSUE TITLE
Error from Zapier

### ISSUE THREAD

**Issue by jean** [pipes-digital/pipes#29]
I'm feeding a pipes feed into Zapier, and today for the first time I got a warning: 

`RSS: ExternalHTTPSConnectionPool(host='www.pipes.digital', port=443): Read timed out. (read timeout=39)`

Is that a sign that Pipes is getting traction? :grin:

**Comment by onli** [comment]
Yeah, maybe ;)

I pushed a change yesterday that improves on GUID creation and media enclosures. If the data in the pipe is very big, maybe that additional computing moves it over the timeout threshold? Could you show the pipe in question?

Though in my testing, I only ran into timeouts when I had feedblocks that were not cached yet, and I just had to call the feed 2-3 times till the cache was filled and the pipe fast enough.

**Comment by jean** [comment]
It's not so big:

[![activity diagram](http://yuml.me/185de0a6.svg)](http://yuml.me/diagram/plain/activity/edit/(Feed%20"github-commits")->(Filter%20"Merge-pull-request")->(Duplicate)->|a|,|a|->(Extract%20"item-title-1")->|b|,|a|->(Extract%20"item-title-2")->|b|,|a|->(Extract%20"item-link-3")->|b|,|b|->(Build%20Feed))

**Comment by onli** [comment]
The github feed does not have more than 10 items? That should not be an issue at all.

Please send me the link to the pipe (if you want to keep it private, send a mail to support@pipes.digital - if you are worried about the token, maybe you could recreate the pipe with a public repo with similar feed length?). I would need this to take a closer look, maybe the timeout is caused by a bug.

**Comment by onli** [comment]
I had a try at recreating the issue, and it seems to work. Maybe I miss something in the diagram? See https://www.pipes.digital/pipe/x3NpGA9B.

**Comment by jean** [comment]
That pipe (and a few others like it) has been working flawlessly for months, this was the first hiccup of any kind.

**Comment by jean** [comment]
Hmm now I'm receiving the warning more often. I'll send links to support.

> We ran into a problem with one of your Zaps:
pipe1: PR merges: RSS to Trello card had 1 error (edit this Zap)
> > Error Message:
> > 	RSS: ExternalHTTPSConnectionPool(host='www.pipes.digital', port=443): Max retries exceeded with url: /feed/k1Nk7XNR (Caused by ConnectTimeoutError(<useful.request_extras.ExternalHTTPSConnection object at 0x7f6dbd0d9290>, 'Connection to www.pipes.digita...

> We ran into a problem with one of your Zaps:
> pipe2: PR merges: RSS to Trello card had 1 error (edit this Zap)
> > Error Message:
> >	RSS: ExternalHTTPSConnectionPool(host='www.pipes.digital', port=443): Max retries exceeded with url: /feed/Y3qRAbO8 (Caused by ConnectTimeoutError(<useful.request_extras.ExternalHTTPSConnection object at 0x7f6a4f9d5a50>, 'Connection to www.pipes.digita...

**Comment by jean** [comment]
No  more errors in the meantime.
