### ISSUE TITLE
Inverse Filter

### ISSUE THREAD

**Issue by agude** [pipes-digital/pipes#3]
Many of the sites I read put their podcast announcements on the same feeds as their articles. I'd love to be able to build something that says "Remove any post that matches..." to remove these! Sort of a block that inverts the current "Keep any post that matches..." provided by `Filter`.

**Comment by onli** [comment]
Hi
Thanks for the suggestion. I agree, that would be a nice feature. It is now on the roadmap.

**Comment by onli** [comment]
The filter block now has a checkbox to activate that behaviour. When toggled, the filter block will not show found items, but instead remove them.

You can also now give it a regular expression. That's optional, it still works also with just a keyword. But a regular expression might make filtering for podcast announcements easier.

**Comment by agude** [comment]
I added the block to my pipes, but it doesn't look like the "status" of the check box is saved. I made a "[Pp]odcast" filter with the box checked (to reject) and saved. However now I'm only getting podcast items, and the box is unchecked again when I load the pipes back up.

**Comment by onli** [comment]
Oh, yes, that was a bug when loading the pipe for the editor. Could you please try again now? It might be necessary to reload the site a few times to make sure the javascript is not served from your browser cache

**Comment by agude** [comment]
Looks like it is working now! Thanks.
