### ISSUE TITLE
Page numbering problem

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#30]
The first page on https://www.pipes.digital/pipes is numbered 0 instead of 1.

**Comment by onli** [comment]
Thank you. This shoulld be fixed now.

PS: Could you send me a mail to info@pipes.digital?

**Comment by anewuser** [comment]
It still shows 0 and 1 to me. I've emailed you.

**Comment by onli** [comment]
Oh, that was not the bug I tried to fix. 0 and 1, that is okay in my eyes given the target users. I understood the original report as not showing the pagination when on the second page.

**Comment by anewuser** [comment]
Ah, sorry. I edited that part out after noticing it had been fixed.

**Comment by anewuser** [comment]
https://www.pipes.digital/pipes?page=0

Top: 0 1
Bottom: 0 1

https://www.pipes.digital/pipes?page=1
Top: 0 1 2
Bottom: 0 1

**Comment by onli** [comment]
Fixed, again. Thanks again for reporting this :)
