### ISSUE TITLE
pipes.digital SSL error: Let's Encrypt cert expired

### ISSUE THREAD

**Issue by jean** [pipes-digital/pipes#31]
The client probably just needs to be restarted .. 

https://www.pipes.digital

NET::ERR_CERT_DATE_INVALID
Subject: pipes.digital
Issuer: Let's Encrypt Authority X3
Expires on: 23 Dec 2017
Current date: 23 Dec 2017

**Comment by onli** [comment]
Hey, thank you for reporting this! I was able to fix it this as soon as you opened this issue, but because of the holidays was blocked from responding to you here, until now :)
