### ISSUE TITLE
Extracting plain dates from downloaded source

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#32]
https://www.pipes.digital/editor/aMOQA3Oe

This page has dates in the American format (`9/21/2017`, `9/16/2017` etc.), but the "Build Feed" block can't currently parse them. Have you considered adding this feature? Users would have to be able to tell if strings are in the international or American format, though.

**Comment by onli** [comment]
Hi. No, I did not have this on my radar.

I found https://github.com/jeremyevans/ruby-american_date, which in my short test seems like it would properly extend the ruby date parser to understand this date format. I will test it out with the whole pipes platform and see whether this is a solution.

**Comment by onli** [comment]
This should work now. Could you confirm?

**Comment by anewuser** [comment]
The dates are off by one day (one day earlier on Pipes):

https://www.pipes.digital/feed/aMOQA3Oe
https://krita.org/en/?post_type=post&s=

**Comment by onli** [comment]
The dates are correct at my side. We are probably in a different time zone, and maybe the Krita site does some voodoo to adjust the dates depending on the timezone of our browser? Krita 4.0 Beta 1 was released on `1/12/2018`, according to the site, and the pipeps feed shows `January 11, 2018` to me.

> I mentioned the need for a toggle because dates like 05/02/2017 can be interpreted in different ways: May 2 in the US and February 5 in other countries.

Right, I forgot about the complexity of that area. But this would need its own date interpretation block, and a very capable gem (I doubt I could get this right if I tried to solve this on my own). I'm not sure how to handle that.

**Comment by anewuser** [comment]
Yes, there's some mix-up with time zones, because the Krita site says `1/11/2018` to me, and the feed source has `Jan 2018 23:00:00 -0000`  on Firefox.

Anyway, this isn't too important since even without dates all future posts would arrive accordingly to one's feed reader. Thank you for adding the possibility to parse the Krita page.
