### ISSUE TITLE
Tagging problems

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#34]
When you start typing in a tag, Pipes suggests tags you've already added.

Also, I'm currently unable to remove tags from https://www.pipes.digital/pipe/YPOdgaND (I added this set of technology-related tags at once from the tag suggestions, just to test it).

Firefox 58.0.1

**Comment by onli** [comment]
What exactly happens if you try to remove the tags? Do you see the minus sign, the button to remove it? Is it clickable? Does the popup appear asking you whether you want to remove the tag? Something in the browser console?

**Comment by anewuser** [comment]
The popup appears, but nothings happens.  No error.

I can actually remove the other tags (English, languages etc.), but not the technology ones that were added altogether via the autocomplete option:

![screenshot](https://user-images.githubusercontent.com/6733770/35822644-126ca27e-0a94-11e8-8795-ef5771021f00.png)

**Comment by onli** [comment]
That was a bug. The tags got splitted on display, but not entry. So he tried to delete the tag `technology`, but the whole string was set as tag.

Thanks for reporting. This should now be fixed, deleting should work.

**Comment by onli** [comment]
For the problem with the already entered tags: This autocompletion is using a simple html5 datalist as a source, and I don't think it is possible (with reasonable effort) to prevent this from happening. That's a minor inconvenience I'd like to ignore :)

**Comment by anewuser** [comment]
Ah, since most sites today make heavy use of libraries and background server requests and whatnot, I assumed the server was queried on each key press. Congratulations on keeping it simple. 

Thanks for fixing the bug.
