### ISSUE TITLE
Get post content from two different HTML elements

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#35]
I'm trying to recreate this feed with Pipes, but the contents for each post come from two separate divs, and apparently you can't do that with Pipes, right?

https://feed43.com/learnersdictionary.xml

https://www.pipes.digital/feed/YPOdgaND

The source URL is: http://www.learnersdictionary.com/qa/post/latest (this always redirect to their most recent article).

Each post body should be generated from `.question` and `.answer` .

I've tried extracting `.question, .answer` with a single block, and extracting them separately and then using a combine block, but both resulted in two separate posts.

**Comment by onli** [comment]
Right, that was not possible so far. I now modified the extract block to support concat(), a xpath function meant to do exactly that. Please see https://www.pipes.digital/pipe/boNyzPOP for an example on how it can be used to combine those `.question` and `.answer`. Hope this helps :)

**Comment by anewuser** [comment]
It works, but there's something else I didn't mention. The HTML tags (`<p>`,`<em>`,`<ul>`) are stripped from the answer code, so paragraphs and lists are lost and everything is put together in a single block. Compare the output:

https://feed43.com/learnersdictionary.xml

https://www.pipes.digital/feed/YPOdgaND

**Comment by onli** [comment]
You're right. And I'm not able to modify that xpath expression to concatenate the html of those elements.

I did enable raw (inner_)html output for regular xpath expressions. So it was definitely useful to look into this. But the concat just does not work like this, at least so far.

I will have to think about the best solution here. Offer a custom concat for the exctract block that preserves the raw content of an element? Have a separate block that can concatenate strings? Is there an alternative to xpath that could be offered as an alternative block?

**Comment by anewuser** [comment]
Wouldn't it be possible to use a simple multiple-element CSS selector like `.question, .answer` in an extract block for this and put them together with their raw code?

Right now this creates two separate feed posts, but is there any case where that's the intended behavior?

**Comment by anewuser** [comment]
I see, so that's by design.  I've been using Feed43 for a long time, but I think that all feeds I've ever created followed a strict pattern. 

I did imagine cases like your example with Pipes users, but thought that people would just extract the different sections into different feed blocks and then recombine them.

As for the new raw blocks, test them with unwanted tags like `script` and `iframe` to make sure there's no security problem. Ideally it would keep just basic tags like `p`, `ul`,  `li`,  `img`, `em`, `strong` and HTML entities (like the `&nbsp;&mdash;&nbsp;` in my feed).



Here's what that feed looks like in the Feed43 editor in case you're curious:

![screenshot](https://user-images.githubusercontent.com/6733770/35836688-cbc76afe-0ac8-11e8-9e84-802e6c61e198.png)

**Comment by onli** [comment]
Thanks for that image, lead me in an interesting direction. I added a merge items block that should solve this use case, see https://www.pipes.digital/pipe/YPOdK0ND

**Comment by anewuser** [comment]
Thanks for looking into ti. The design of your link is broken on my 1366x768 screen, though. I can't see the last block or move it. I've tried it on Firefox and Opera:

![screenshot](https://user-images.githubusercontent.com/6733770/36334055-ae8a4ac8-1361-11e8-83c9-cda3c2c93301.png)

**Comment by onli** [comment]
If you use a different browser than Firefox you could click on the blue background and drag it around (there is a bug in FF preventing that to work). But that block is just a feed builder block, merge items connects to the content input.

**Comment by anewuser** [comment]
I know the point was to show me the new feature, sorry. I just wanted to report the resolution bug before I had some time to test it.

You've used xpath in your example, but actually simple `.class` selectors work too. 

Here's the final feed: https://www.pipes.digital/pipe/YPOdgaND

Thanks a lot. 😄
