### ISSUE TITLE
Download block not connecting to Duplicate block

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#36]
I'm currently unable to connect a new Download block to a Duplicate block on Firefox 58.0.1. The connectors don't get highlighted, as if it was impossible to do that.

Cloning an existing pipe where they are already connected works.

**Comment by onli** [comment]
Yes, that changed a few versions ago. The goal was to make sure that users connect only feeds to those pipes that only understands feeds. That enabled to better define how other formats can be supported (by converting them in the extract block).

Workaround here is to use multiple download blocks. Downloads are cached anyway, there is no performance impact, it is only slightly messier.

**Comment by anewuser** [comment]
I see. Will existing feeds continue to work?

**Comment by onli** [comment]
Yes, definitely. This change is already a few month old :)
