### ISSUE TITLE
Concatenate or just link text input to download block

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#37]
I've made this to monitor new subtitles:

https://www.pipes.digital/pipe/j1O4Ve9d

Film pages have clean URLs like:

https://subscene.com/subtitles/metropolis
https://subscene.com/subtitles/the-general-1926

To avoid having to create new pipes for every new film I want to monitor, using a dynamic input block sounds a good idea.

However, input blocks can't be linked to download blocks. If you believe that letting people input full custom URLs could cause problems, what about having a way to at least concatenate a text input with a download block , so that I could have a download block like this:

`https://subscene.com/subtitles/` + text input (e.g. `metropolis`, `the-general-1926` etc.)

**Comment by onli** [comment]
There is no deeper reason why text input blocks can't be connected to download blocks, this is merely a bug. I will look into this.

**Comment by onli** [comment]
This will work now. Be sure to manually reload the page to clear the cached javascript.

**Comment by anewuser** [comment]
Thank you! Just make sure that the current string in the Download block is deleted when these two kinds of blocks are linked, or it causes a server error in the output.

**Comment by anewuser** [comment]
Can you tell me why it's giving server errors? https://www.pipes.digital/pipe/j1O4Ve9d

Entering the same URL in the download block (without the text input) worked.

**Comment by onli** [comment]
I see nothing wrong with it, apart from that currently the text input block is not connected to the download block. Might it be just that? 

If you just disconnected the text input block later on, could you please share the pipe? It would make debugging easier.

**Comment by anewuser** [comment]
It seems there was some problem when I saved the pipe with text inputs (at least with the combination of block types I used in this pipe), because I did connect those blocks, and they were reset to unconnected twice... then it happened again with a second text input I added. 

I'm not sure if this problem was on my side, since Firefox is set not to keep any cache after closed, and I restarted it a few times during this process. I'll report if anything like that happens again. 

Anyway, the feed is now working: https://www.pipes.digital/pipe/j1O4Ve9d :)

There's only a minor thing: the input seems to be case-sensitive:

https://www.pipes.digital/feed/j1O4Ve9d?Subscene+link=https%3A%2F%2Fsubscene.com%2Fsubtitles%2Fmetropolis&Language=Italian

https://www.pipes.digital/feed/j1O4Ve9d?Subscene+link=https%3A%2F%2Fsubscene.com%2Fsubtitles%2Fmetropolis&Language=italian

**Comment by onli** [comment]
I'm happy it works now.

> I'll report if anything like that happens again.

Please do. That has the potential to be a very annoying bug, but I did not see it at all so far.

> There's only a minor thing: the input seems to be case-sensitive:

I would assume that comes from the subscene website, or is that one not case sensitive?

**Comment by anewuser** [comment]
I mean that entering either "Italian" or "italian", or "Trump" or "trump" in your own example, should work:

https://www.pipes.digital/feed/14OE65qg?feed=http%3A%2F%2Frss.nytimes.com%2Fservices%2Fxml%2Frss%2Fnyt%2FHomePage.xml&filterterm=trump

https://www.pipes.digital/feed/14OE65qg?feed=http%3A%2F%2Frss.nytimes.com%2Fservices%2Fxml%2Frss%2Fnyt%2FHomePage.xml&filterterm=Trump

**Comment by onli** [comment]
For the filterblock, they just are case sensitive. You can make them case insensitive by using a regexpression, by writing `/keyword/i`. See here: https://www.pipes.digital/feed/14OE65qg?feed=http%3A%2F%2Frss.nytimes.com%2Fservices%2Fxml%2Frss%2Fnyt%2FHomePage.xml&filterterm=/trump/i

**Comment by anewuser** [comment]
I see. Is there any specific reason why you don't want to make it case-insensitive by default when connected to text inputs?

**Comment by onli** [comment]
It would be very hard to trigger case-sensitivity that way around. As it is now that just comes by default from supporting regexpression.

**Comment by anewuser** [comment]
Thanks for the replies!
