### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by sharkoz** [pipes-digital/pipes#4]
Hi,

My feed doesn't work (https://www.pipes.digital/feed/j1O4yeqd ) it returns an error (Internal Server Error) but I don't know why...
It looks like it is because of the filter, maybe I am using it wrong ?

Any idea ?

Thanks

**Comment by onli** [comment]
You used it correctly. The filter block did not properly convert the feed date, which the test feeds just do not set. I fixed that just now, your pipe does no longer throw an error for me.

**Comment by sharkoz** [comment]
Amazing reactivity ! Thanks :)

**Comment by onli** [comment]
:) Thanks for reporting the issue. I will close here, but just re-open this issue if the error re-appears.
