### ISSUE TITLE
Undo option

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#40]
Sometimes I disconnect or delete a block accidently, and need to discard the other changes I've made to get it back.

Would it be possible to add an "undo" option?

**Comment by onli** [comment]
Maybe, it would be a big task. But also a nice feature, so worth investigating.

**Comment by onli** [comment]
I just activated an undo option. When removing a block, a small notification will pop up at the top for 5 seconds, which contains an undo button and the hint that Ctrl + Z works as well. 

I'm not sure if this captures completely the scenario you describe?

**Comment by anewuser** [comment]
Thanks!
