### ISSUE TITLE
Add more connectors to the "Combine" block on demand

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#41]
When you connect 5 blocks to a `Combine` block, it could automatically show a 6th connector in case you want to add another source to it, and then a 7th connector, and so on, up to the number of sources you're willingly to allow people to use in a single pipe.

I had to add a second `Combine` step to this feed because of that: https://www.pipes.digital/pipe/DpOrjQOw

**Comment by onli** [comment]
Hi. I just pushed an update that enables this feature, and also adds more connectors to the duplicate block.
