### ISSUE TITLE
The certificate expired on Saturday, April 21, 2018

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#42]
`Error code: SEC_ERROR_EXPIRED_CERTIFICATE`

**Comment by jean** [comment]
www.pipes.digital uses an invalid security certificate. The certificate expired on April 22, 2018, 6:41 AM. The current time is April 25, 2018, 4:06 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by jean** [comment]
See #31 ..

**Comment by anewuser** [comment]
The error shows the expiration date in your own time zone. That's why it said "April 21" to me.

**Comment by onli** [comment]
This works for me, I see a current certificate valid till June 21. Did that fix itself automagically during the last 44 minutes? 

> See #31 .. put letsencrypt in the crontab ;-)

It is :) But the issue might be somewhere else.

**Comment by anewuser** [comment]
I use Firefox. 

It's fixed for me too now

**Comment by onli** [comment]
Strange issue though. Thanks for the report, and please keep me posted if this happens again.

**Comment by jean** [comment]
In my case it wasn't a browser issue, the error was coming from Zapier. (In fact I'm going github->pipes->zapier->trello.)

> Zap Alert!We ran into a problem with one of your Zaps:
> [...] had 1 error (edit this Zap)
>                       Error Message:
>                             RSS: Could not verify SSL certificate. Please check certificate installation for domain!

**Comment by anewuser** [comment]
@onli I'm getting this error again. Please check it.

**Comment by onli** [comment]
Thanks!

**Comment by anewuser** [comment]
@onli expired again.

**Comment by onli** [comment]
damn. Now I have to figure out hwy the monitoring failed. Thank you though! :)
