### ISSUE TITLE
Feed viewer

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#46]
Firefox has removed the built-in feed viewer, and now it's become harder to quickly verify changes to your pipes, since external services and readers may cache them. Would it be possible for you to add a formatted viewer like this to Pipes, so that we don't have to install an extra extension just for this?

![live-bookmarks](https://user-images.githubusercontent.com/6733770/50572851-32d90780-0db0-11e9-8f0b-a5699737bef5.jpg)

**Comment by onli** [comment]
Happy new year! I was never certain Firefox will really also remove the RSS viewer function and not just the Live bookmarks. It's a shame.

Yes, I think I can introduce an intermediate page that displays the feeds and has an option at the top to download the original file. Might even be the same mechanism that will allow to improve the block inspector.

**Comment by anewuser** [comment]
Yes, I feel the same way about their recent feature removals. 

Happy new year. I wasn't sure if you were on vacations from Github. 😄

**Comment by onli** [comment]
I indeed just came back from a vacation, but always had an eye on this repo :)

https://www.pipes.digital/feedpreview/VNzYZg94 is the current implementation, it is accessible by clicking on the feed button on https://www.pipes.digital/pipe/VNzYZg94, the pipe page. Also the "Pipe Output" link in the editor will now point to such an intermediary page.

Does this work for you?

**Comment by onli** [comment]
Great idea, it's added.

**Comment by anewuser** [comment]
@onli  Try to generate a feed with this pipe: https://www.pipes.digital/pipe/k0OolxqK

Firefox 64 attempts to download the file.

**Comment by onli** [comment]
The feed button leads to https://www.pipes.digital/feedpreview/k0OolxqK, that opens a download prompt for you?

**Comment by anewuser** [comment]
The feed button works and shows the SoundCloud profile I've set as the default one. I'm talking about the form to generate a feed for another profile.

**Comment by onli** [comment]
That was almost completely in place already. I added the missing pieces and pushed it online. The form will now lead to the feedpreview, and also the raw feed link there gets the new params to not point to the default raw feed.

**Comment by anewuser** [comment]
@onli It isn't getting the parameters. Check https://www.pipes.digital/feedpreview/k0OolxqK?Tracks+URL=https%3A%2F%2Fsoundcloud.com%2Fglobalriddims&Title=Global+Riddims :

` <link rel="alternate" type="application/rss+xml" href="https://pipes.digital/feed/k0OolxqK" />`

**Comment by onli** [comment]
Right! Thanks, that's missing the params.

**Comment by onli** [comment]
The href contains not the parameters exactly like the button to the raw feed. Does it work in your feed reader?

**Comment by anewuser** [comment]
Yes, it seems to be working. Thanks!
