### ISSUE TITLE
Authorship lost in manipulated pipes

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#50]
Compare these:

https://www.pipes.digital/pipe/l9vz5191 - no manipulations after the `Combine` block

![author](https://user-images.githubusercontent.com/6733770/53123004-d33ce400-3536-11e9-8221-29a74f687cc3.png)

https://www.pipes.digital/pipe/MOlEE5qD - full pipe with manipulations

![no author](https://user-images.githubusercontent.com/6733770/53123092-01babf00-3537-11e9-997b-efa0b1bf0adb.png)

**Comment by onli** [comment]
Thanks for reporting this, I will fix it soon.

**Comment by onli** [comment]
It was actually the sort block that ate the author information, I fixed that now.
