### ISSUE TITLE
New element picker and capitalization of selectors

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#51]
* Create a `Download` block with `https://www.designer.io/changelog/`
* Use the element picker in an `Extract` block to select a post title (e.g. `Version 2019-1.4`)

It creates a rule for `H3`. `View output` is blank.

If you change that to `h3`, `View output` loads all entries accordingly.

**Comment by onli** [comment]
Right, nokogiri behaves different than I expected here. The selector with `H3` works just fine in the browser, but not with nokogiri in the pipes backend. I changed the select library (https://github.com/pipes-digital/pipe-select) to lowercase the selector when picking a node name as selector, like here.

The js library is loaded in an iframe, you might need to clear the cache to get the current version.

Thanks for catching this incomptability!
