### ISSUE TITLE
Rename or label feed blocks

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#52]
Pipes with several Youtube feeds are hard to manage because most channels don't have readable IDs:

![youtube feeds](https://user-images.githubusercontent.com/6733770/54468836-921fa480-476f-11e9-8436-f79bb752dd2f.png)

**Comment by onli** [comment]
That function just got added! A small edit button (UTF-8 pencil icon) should appear after a reload in the block title. It allows to edit a block, the title is persistent after saving the pipe once.

**Comment by anewuser** [comment]
Thanks. It's hard to move a renamed block because clicking on a letter in the title selects it on Firefox.

![pipe](https://user-images.githubusercontent.com/6733770/63899936-2ce60580-c9d5-11e9-9049-e004294fc3c2.gif)

**Comment by onli** [comment]
Right, thanks (useful gif!). I fixed this now.
