### ISSUE TITLE
Requesting permission to expose a Pipes feed to a very large audience

### ISSUE THREAD

**Issue by 75th** [pipes-digital/pipes#53]
As previously discussed, I'm using Pipes to combine the free feed of Chapo Trap House with my own private Patreon subscription. Chapo Trap House is the second most popular creator on Patreon, with almost 28,000 patrons.

The /r/chapotraphouse subreddit has almost 94,000 subscribers, and I was thinking about sharing a version of my Pipe there that uses a Text Input node to let people query their own private URLs.

Fortunately I realized before posting that these numbers are very large, and you might not like this kind of server load from largely non-technical users, caused by someone who's still on the free plan.

So I thought I'd ask before doing anything. Should I do this, or should I attempt to delete the idea from my brain as fast as possible?

**Comment by onli** [comment]
That's something the system just has to manage and if it can't right now, something to learn that it has to be improved. So sure, go ahead :)

Could you share your pipe here or per email (support@pipes.digital) so that I can have a look at the blocks in play? 

In any case, thanks for the heads up!

**Comment by 75th** [comment]
No problem, and thank you! The pipe ID is 7N3mlbqy .
