### ISSUE TITLE
Language translation block

### ISSUE THREAD

**Issue by frou** [pipes-digital/pipes#54]
Would a language translation block be feasible? e.g. take an input feed and translate the Title of each entry to English.

**Comment by onli** [comment]
I'm not sure it's feasible, but from what blocks can do it could work and fit well. Do you have a tool or service in mind that would be ideal to handle the translation?

**Comment by frou** [comment]
I was assuming there would be server-side libraries that could do translation without making network requests to a third-party API. But upon searching just now I'm surprised to find that doesn't really seem to be the situation!
