### ISSUE TITLE
Feed URL with expired certificate breaks entire pipe

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#55]
If a feed block contains a URL with an expired certificate (current example: https://ugetdm.com/feed/), this will break a combine block and the entire pipe. It just outputs `Internal Server Error`.

**Comment by onli** [comment]
The URL with the expired certificate should not cause a 500, but be treated as an empty feed/site. I will look into this.

**Comment by onli** [comment]
I added some error handling for this. In my test case, simply outputting nothing worked best. Does it also work for you?

**Comment by anewuser** [comment]
Yes, that URL now is ignored. Thanks!
