### ISSUE TITLE
Missing block connections

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#57]
The pipe I used as an example for the last issue is still working (check its feed), but when I try to edit it, it doesn't show the connections between each block: https://www.pipes.digital/pipe/E9DvA6Oj

![pipe](https://user-images.githubusercontent.com/6733770/63811126-fa68d980-c8fc-11e9-8a56-0a9d129b040b.png)

**Comment by onli** [comment]
I can confirm this issue. Puzzling, how did it arrive at that state, that should not be possible? I will have to debug this a bit.

**Comment by anewuser** [comment]
I'm not sure. The last change I've made was removing the uGet feed.

**Comment by anewuser** [comment]
Since I can't reproduce that problem and that pipe was too messy, I've replaced it with a new one I've made from scratch (https://www.pipes.digital/feedpreview/7N3mXLqy).

If I find any other issue, I'll report it to you.

**Comment by onli** [comment]
Alright, Thanks! I also had no luck reproducing this.
