### ISSUE TITLE
Filters based on categories

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#58]
Can you add `item.category` support for filters? Blogger and Wordpress use different syntaxes, so this should include everything within the  `category` tag:

http://www.bassblog.pro/feeds/posts/default
```
<category scheme="http://www.blogger.com/atom/ns#" term="320 kbps"/>
<category scheme="http://www.blogger.com/atom/ns#" term="drum and bass"/>
<category scheme="http://www.blogger.com/atom/ns#" term="liquid"/>
```
https://bassandspace.com/
```
<category><![CDATA[AIFF]]></category>
<category><![CDATA[ALAC]]></category>
<category><![CDATA[Bandcamp]]></category>
<category><![CDATA[Free download]]></category>
```

**Comment by onli** [comment]
Hi. I just added support for filtering by categories. Pipes did not conserve categories so far, this got added to all blocks, and the filter block now has the option to select that field.

**Comment by anewuser** [comment]
Thank you!
