### ISSUE TITLE
Output preview stays on screen after block is removed

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#63]
I've found this bug:

![pipes](https://user-images.githubusercontent.com/6733770/81506405-6e50e380-92cc-11ea-95fc-8646ab72a5b1.gif)

This happened while I was editing one of my larger pipes. After I saved it, some block connections went missing (as in #57) and I had to connect them again.

Thanks for the heads-up about the repository. You should promote it again on Hacker News, Slashdot and Reddit.

**Comment by onli** [comment]
This should be fixed now, at least the inspector not closing.
