### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#72]
Pipes doesn't remember my login info anymore and I have to get a new code every time I close Firefox.

I tried to log in right now, and it redirected me to a blank `https://www.pipes.digital/_browserid_assert` page.

**Comment by anewuser** [comment]
Alright, I was able to access my account normally today.

**Comment by onli** [comment]
Excellent :)

**Comment by anewuser** [comment]
@onli Please check if the login system is working properly. It isn't sending any emails to my @protonmail.com address.

**Comment by onli** [comment]
Hi @anewuser, no, it's not working properly. There is a problem with the email delivery service the portier broker uses. Gmail login will still work, if you have an account to switch over (as that uses OIDC instead of sending a mail), I'm looking into the options now.

**Comment by onli** [comment]
Update: It took way too much work, but I now moved Pipes over to our own portier broker. The login should work now again. Can you confirm?

**Comment by anewuser** [comment]
I got a login link right away. Thank you!
