### ISSUE TITLE
Post publication dates assigned to feeds built without dates

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#73]
Where are the dates for these posts coming from? The pipe editor shows different dates from the feed output, but the latest entries are actually from this week: https://www.pipes.digital/pipe/3NpgYr9B

**Comment by onli** [comment]
When a feed builder block gets no date input, it will use now() as a date. But those dates get cached when an item is first created, for each individual block. 

The cache key uses the guid. The guid of the content items is re-used, if it's not there or the block has the "recalculate guid" option it gets computed by the hash of content and title. Is it possible that guid is not a global unique id in that feed, but gets repeated instead?

**Comment by anewuser** [comment]
This pipe downloads web pages, and each item has a unique title and link, so I don't know why those recent posts had 2020 dates. Anyway, I've enabled "Recalculate GUID", and the dates changed. I'll monitor it to see if future entries are added properly.

**Comment by anewuser** [comment]
I'm facing this issue again with the same pipe: https://www.pipes.digital/feedpreview/3NpgYr9B

I've added the length ( `.player_standard_tool__time` ) of each audio file to their titles to try to generate new guids, but it made no difference.

**Comment by anewuser** [comment]
Duplicating the pipe made it add today's date to each item ([1NklaJOR](https://www.pipes.digital/pipe/1NklaJOR)).

**Comment by onli** [comment]
Duplicating the pipe would reset the cache. Strange that it was necessary. Hope to find the issue sometime.
