### ISSUE TITLE
Filter using item descriptions

### ISSUE THREAD

**Issue by anewuser** [pipes-digital/pipes#74]
https://www.youtube.com/channel/UCQRnnO-TlbPKhlIjp04TnWg/videos - videos with `ASMR` in the description can't currently be blocked, not even with `search in fields: all`.

**Comment by onli** [comment]
Confirmed! Will have a look. This should work already.

**Comment by onli** [comment]
This should work now, in that the filter block now also filters the description field.

Careful though: The YT feed has that data in media:description, and that field gets ignored by the filter block. Pipes will automatically move that field to description, but not immediately when the data leaves the feed block. In my test pipe I chained two filter blocks together (with the first only being there to let Pipes transform the feed), then it worked. You could also do that manually with an extract block.

**Comment by anewuser** [comment]
Thank you!
